@base = http://localhost:3000
@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjd9.Fc0QeF1GgI7TbPKK81a4WOHgIq8WBKF7B04Nbpa7acA

### 注册
POST {{base}}/user/register
Content-Type: application/json

{
    "email": "4131144633@qq.com",
    "password": "123123"
}

### 用户信息
GET {{base}}/user/info
Authorization: Bearer {{token}}