worker_processes auto;
events { }
http {
    include /etc/nginx/mime.types;
    default_type application/octet-stream;

    # 由构建参数选择：prod → chef.hetou.vip；test → test.hetou.vip
    include /etc/nginx/conf.d/site.conf;
}
